---
title: "rural.Rmd"
output: html_document
date: '2022-06-30'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, echo = FALSE}
rural = get_decennial(geography = "state",
              variables = c("P001001", "P002005"),
              year = 2010,
              output = "wide",
              geometry = TRUE)
rural |>  
  filter(!NAME == "Alaska", !NAME == "Peurto Rico",
         !NAME == "Hawaii") |> 
  ggplot(aes(fill = (P002005/P001001) * 100)) +
  geom_sf() +
  scale_fill_viridis_c(option = "plasma", direction = -1) +
  theme_void() +
  labs(title = "Rural geography of the United States",
       fill = "Percent Rural",
       caption = "Source: Census 2010")
```
```{r}
rural = get_decennial(geography = "state",
              variables = c("P001001", "P002005"),
              year = 2010,
              output = "wide",
              geometry = TRUE) |> 
        shift_geometry()
rural |> 
  ggplot(aes(fill = (P002005/P001001) * 100)) +
  geom_sf() +
  scale_fill_viridis_c(option = "plasma", direction = -1) +
  theme_void() +
  labs(title = "Rural geography of the United States",
       fill = "Percent Rural",
       caption = "Source: Census 2010") 
```

